### PR TITLE
Added support for '.txt' extension format for reports

### PR DESCRIPTION
**Pull request by etsinko**

### CODE REVIEW

**Comment by sebalix** [comment]
Hi,

Can you give me an example of txt report in Odoo?

**Comment by etsinko** [comment]
Not in vanilla Odoo. I'm using https://github.com/WillowIT/Pentaho-reports-for-OpenERP module which compiles txt reports for Zebra printers.

**Comment by sebalix** [comment]
Okay, thanks for the info. Can you make the PR against the `develop` branch instead? I will merge it.

**Comment by sebalix** [comment]
Merged in #20

**Pull request closed without merging**
